# Web Scrapping Assignment 4

Name:-Parth Gadhvi

Batch:- 2307

## Questions

1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url =
https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:

 A) Rank

 B) Name

 C) Artist

 D) Upload date

 E) Views

In [1]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [2]:
#opening the website page
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [3]:
#Extracting Rank
rank=[i.text.strip('.') for i in driver.find_elements(By.XPATH,'//tbody/tr/td[1]')[:30]]

#Extracting Name
name =[i.text.split('[')[0] for i in driver.find_elements(By.XPATH,'//tr/td[2]')[:30]]

#Extracting Artist
artist = [i.text for i in driver.find_elements(By.XPATH,'//tr/td[3]')[:30]]

#extracting views
viewsBillions =[i.text for i in driver.find_elements(By.XPATH,'//tr/td[4]')[:30]]

#extracting Upload Date
uploadDate=[i.text for i in driver.find_elements(By.XPATH,'//tr/td[5]')[:30]]

driver.close()

print(len(rank),len(name),len(artist),len(viewsBillions),len(uploadDate))

30 30 30 30 30

In [4]:
Most_viewed_videos_on_YouTube = pd.DataFrame({
    "Rank":rank,
    "Name": name,
    "Artist": artist,
    "Upload Date": uploadDate,
    "Views In Billions": viewsBillions
})

#set rank as index
Most_viewed_videos_on_YouTube = Most_viewed_videos_on_YouTube.set_index('Rank')
Most_viewed_videos_on_YouTube

,Name,Artist,Upload Date,Views In Billions
Rank,,,,
,This section's factual accuracy may be comprom...,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",13.36
1,"""Baby Shark Dance""",Luis Fonsi,"January 12, 2017",8.26
2,"""Despacito""",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.80
3,"""Johny Johny Yes Papa""",Cocomelon - Nursery Rhymes,"May 2, 2018",6.41
4,"""Bath Song""",Ed Sheeran,"January 30, 2017",6.08
5,"""Shape of You""",Wiz Khalifa,"April 6, 2015",6.03
6,"""See You Again""",Cocomelon - Nursery Rhymes,"May 24, 2018",5.56
7,"""Wheels on the Bus""",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.48
8,"""Phonics Song with Two Words""",Mark Ronson,"November 19, 2014",5.03
9,"""Uptown Funk""",Miroshka TV,"February 27, 2018",4.97
10,"""Learning Colors – Colorful Eggs on a Farm""",officialpsy,"July 15, 2012",4.90
11,"""Gangnam Style""",Get Movies,"January 31, 2012",4.56
12,"""Masha and the Bear – Recipe for Disaster""",Ultra Records,"April 5, 2018",4.44
13,"""Dame Tu Cosita""",Crazy Frog,"June 16, 2009",4.06
14,"""Axel F""",Maroon 5,"January 14, 2015",3.93
15,"""Sugar""",OneRepublic,"May 31, 2013",3.87
16,"""Counting Stars""",Katy Perry,"September 5, 2013",3.87
17,"""Roar""",Cocomelon - Nursery Rhymes,"June 25, 2018",3.78
18,"""Baa Baa Black Sheep""",Shakira,"June 4, 2010",3.73
19,"""Waka Waka (This Time for Africa)""",Justin Bieber,"October 22, 2015",3.71
20,"""Sorry""",Jingle Toons,"June 14, 2018",3.69
21,"""Lakdi Ki Kathi""",Ed Sheeran,"October 7, 2014",3.66
22,"""Thinking Out Loud""",Katy Perry,"February 20, 2014",3.59
23,"""Dark Horse""",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.55
24,"""Humpty the train on a fruits ride""",Ed Sheeran,"November 9, 2017",3.54
25,"""Perfect""",Alan Walker,"December 3, 2015",3.51
26,"""Faded""",Passenger,"July 25, 2012",3.51
27,"""Let Her Go""",Maroon 5,"May 31, 2018",3.48
28,"""Girls Like You""",Major Lazer Official,"March 22, 2015",3.46
29,"""Lean On""",Enrique Iglesias,"April 11, 2014",3.45



2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:

 A) Match title (I.e. 1 ODI)
 
 B) Series
 
 C) Place
 
 D) Date
 
 E) Time
 
 Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [8]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get("https://www.bcci.tv/")

In [9]:
#opening the International Page
international = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
international.click()

In [10]:
#accepting cooking
try:
    cookie=driver.find_element(By.XPATH,'//button[@class="cookie__accept btn btn-primary"]')
    cookie.click()
except NoSuchElementException:
    print('No Exception Occured')

# CLicking more button
while(True):
    try:
        more = driver.find_element(By.XPATH,'//button[@class="match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3"]')
        more.click()
    except NoSuchElementException:
        break
        
#Extracting match Title
match=[i.text.strip(' -') for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')]

#Extracting Series
series = [i.text for i in driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')]

#Extracting Place
place = [i.text.split(' -')[1] for i in driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')]

# Extracting Date
date = [i.text for i in driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')]

# Extracting Time
time = [i.text for i in driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')]

driver.close()

print(len(match),len(series),len(place),len(date),len(time))

internationalfixtures=pd.DataFrame({
    "Match Title": match,
    "Series": series,
    "Place": place,
    "Date": date,
    "Time":time
})
internationalfixtures

37 37 37 37 37

,Match Title,Series,Place,Date,Time
0,Quarter Final 1,19TH ASIAN GAMES HANGZHOU 2022,"Pingfeng Cricket Field, Hangzhou",21 SEP 2023,6:30 AM IST
1,1st ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,...",22 SEP 2023,1:30 PM IST
2,2nd ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Holkar Cricket Stadium, Indore",24 SEP 2023,1:30 PM IST
3,3rd ODI,AUSTRALIA TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium, Rajkot",27 SEP 2023,1:30 PM IST
4,1st ODI,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,"Barsapara Cricket Stadium, Guwahati",30 SEP 2023,2:00 PM IST
5,1st T20I,19TH ASIAN GAMES HANGZHOU 2022,"Pingfeng Cricket Field, Hangzhou",3 OCT 2023,6:30 AM IST
6,2nd ODI,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,"Greenfield International Stadium, Thiruvanant...",3 OCT 2023,2:00 PM IST
7,1st ODI,ICC MENS WORLD CUP 2023,"MA Chidambaram Stadium, Chennai",8 OCT 2023,2:00 PM IST
8,2nd ODI,ICC MENS WORLD CUP 2023,"Arun Jaitley Stadium, Delhi",11 OCT 2023,2:00 PM IST
9,3rd ODI,ICC MENS WORLD CUP 2023,"Narendra Modi Stadium, Ahmedabad",14 OCT 2023,2:00 PM IST
10,4th ODI,ICC MENS WORLD CUP 2023,"Maharashtra Cricket Association Stadium, Pune",19 OCT 2023,2:00 PM IST
11,5th ODI,ICC MENS WORLD CUP 2023,"Himachal Pradesh Cricket Association Stadium,...",22 OCT 2023,2:00 PM IST
12,6th ODI,ICC MENS WORLD CUP 2023,Bharat Ratna Shri Atal Bihari Vajpayee Ekana ...,29 OCT 2023,2:00 PM IST
13,7th ODI,ICC MENS WORLD CUP 2023,"Wankhede Stadium, Mumbai",2 NOV 2023,2:00 PM IST
14,8th ODI,ICC MENS WORLD CUP 2023,"Eden Gardens, Kolkata",5 NOV 2023,2:00 PM IST
15,9th ODI,ICC MENS WORLD CUP 2023,"M Chinnaswamy Stadium, Bengaluru",12 NOV 2023,2:00 PM IST
16,1st T20I,AUSTRALIA TOUR OF INDIA 2023-24,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stad...,23 NOV 2023,7:00 PM IST
17,2nd T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Greenfield International Stadium, Thiruvanant...",26 NOV 2023,7:00 PM IST
18,3rd T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Barsapara Cricket Stadium, Guwahati",28 NOV 2023,7:00 PM IST
19,4th T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Vidarbha Cricket Association Stadium, Nagpur",1 DEC 2023,7:00 PM IST
20,5th T20I,AUSTRALIA TOUR OF INDIA 2023-24,"Rajiv Gandhi International Stadium, Hyderabad",3 DEC 2023,7:00 PM IST
21,1st T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"Kingsmead, Durban",10 DEC 2023,9:30 PM IST
22,2nd T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"St George's Park, Gqeberha",12 DEC 2023,9:30 PM IST
23,3rd T20I,INDIA TOUR OF SOUTH AFRICA 2023-24,"The Wanderers Stadium, Johannesburg",14 DEC 2023,9:30 PM IST
24,1st ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,Johannesburg,17 DEC 2023,2:00 PM IST
25,2nd ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,"St George's Park, Gqeberha",19 DEC 2023,2:00 PM IST
26,3rd ODI,INDIA TOUR OF SOUTH AFRICA 2023-24,"Boland Park, Paarl",21 DEC 2023,2:00 PM IST
27,1st Test,INDIA TOUR OF SOUTH AFRICA 2023-24,"SuperSport Park, Centurion",26 DEC 2023,1:30 PM IST
28,2nd Test,INDIA TOUR OF SOUTH AFRICA 2023-24,"Newlands, Cape Town",3 JAN 2024,1:30 PM IST
29,1st T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"Punjab Cricket Association IS Bindra Stadium,...",11 JAN 2024,7:00 PM IST
30,2nd T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"Holkar Cricket Stadium, Indore",14 JAN 2024,7:00 PM IST
31,3rd T20I,AFGHANISTAN TOUR OF INDIA 2023-24,"M Chinnaswamy Stadium, Bengaluru",17 JAN 2024,7:00 PM IST
32,1st Test,ENGLAND TOUR OF INDIA 2023-24,"Rajiv Gandhi International Stadium, Hyderabad",25 JAN 2024,9:30 AM IST
33,2nd Test,ENGLAND TOUR OF INDIA 2023-24,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stad...,2 FEB 2024,9:30 AM IST
34,3rd Test,ENGLAND TOUR OF INDIA 2023-24,"Saurashtra Cricket Association Stadium, Rajkot",15 FEB 2024,9:30 AM IST
35,4th Test,ENGLAND TOUR OF INDIA 2023-24,"JSCA International Stadium Complex, Ranchi",23 FEB 2024,9:30 AM IST
36,5th Test,ENGLAND TOUR OF INDIA 2023-24,"Himachal Pradesh Cricket Association Stadium,...",7 MAR 2024,9:30 AM IST

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
 A)Rank

 B) State

 C) GSDP(18-19)- at current prices

 D) GSDP(19-20)- at current prices

 E) Share(18-19)

 F) GDP($ billion)

 Note: - From statisticstimes home page you have to reach to economy page through code.

In [25]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get("https://www.statisticstimes.com/")

In [26]:
#clicking Economy
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()

#Clicking on India
india=driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india.click()

In [28]:
GDP=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

#Extracting the details
rank = []
state = []
gsdp_18 = []
gsdp_19 = []
shares = []
gdp = []

#Extracting the rank details
try:
    rank_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[1]")
    for ra in rank_tags:
        rank.append(ra.text)
except NoSuchElementException:
    Company.append('NA')
    
#Extracting state name details
try:
    state_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[2]")
    for st in state_tags:
        state.append(st.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting gsdp 2019-20
try:
    gsdp_19_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[3]")
    for g in gsdp_19_tags:
        gsdp_19.append(g.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting gsdp 2018-19
try:
    gsdp_18_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[4]")
    for gs in gsdp_18_tags:
        gsdp_18.append(gs.text)
except NoSuchElementException:
    Company.append('NA')
    
#Extracting share details
try:
    shares_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[5]")
    for sh in shares_tags:
        shares.append(sh.text)
except NoSuchElementException:
    Company.append('NA')

#Extracting GDP details
try:
    gdp_tags = driver.find_elements(By.XPATH,"//div[@id = 'table_id_wrapper']/table/tbody/tr/td[6]")
    for gd in gdp_tags:
        gdp.append(gd.text)
except NoSuchElementException:
    Company.append('NA')

gdp_india = pd.DataFrame({'Rank':rank,'State':state,'GSDP 2019-20(Cr INR at Current Price)':gsdp_19,'GSDP 2018-19(Cr INR at Current Price)':gsdp_18,'Share(%)':shares,'GDP($billion)':gdp})
gdp_india

,Rank,State,GSDP 2019-20(Cr INR at Current Price),GSDP 2018-19(Cr INR at Current Price),Share(%),GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:


  A) Repository title

  B) Repository description

  C) Contributors count

  D) Language used 

  Note: - From the home page you have to click on the trending option from Explore menu through code.

In [32]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get("https://github.com/")

In [33]:
#Clicking Open Source
source =driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
source.click()

#clicking Trending
trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [34]:
#Extracting title
title=[i.text for i in driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')]

#Extracting Description
description = []

for item in driver.find_elements(By.XPATH, '//article[@class="Box-row"]'):
    try:
        des = item.find_element(By.XPATH, './/p[@class="col-9 color-fg-muted my-1 pr-4"]')
        description.append(des.text)
    except NoSuchElementException:
        description.append('-')
        
#Extracting Contributors count
count=[i.text for i in driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/a')]
contri=count[::2]

#Extracting Language
lang = []
for items in driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]'):
    try:
        l= items.find_element(By.XPATH,'./span/span[2]')
        lang.append(l.text)
    except NoSuchElementException:
        lang.append('-')
        
driver.close()
print(len(title), len(description), len(contri), len(lang))

#Converting it into DataFrame:
trending_repositories = pd.DataFrame({
    "Repository Title":title,
    "Repository Description": description,
    "Contributors Count" : contri,
    "Language" : lang
})

trending_repositories

25 25 25 25

,Repository Title,Repository Description,Contributors Count,Language
0,hyperdxio / hyperdx,"Resolve production issues, fast. An open sourc...","2,452",TypeScript
1,williamyang1991 / Rerender_A_Video,[SIGGRAPH Asia 2023] Rerender A Video: Zero-Sh...,"1,076",Jupyter Notebook
2,NExT-GPT / NExT-GPT,Code and models for NExT-GPT: Any-to-Any Multi...,773,Python
3,makeplane / plane,"🔥 🔥 🔥 Open Source JIRA, Linear and Height Alte...","15,477",TypeScript
4,grafana / beyla,eBPF-based autoinstrumentation of HTTP and HTT...,428,C
5,CorentinJ / Real-Time-Voice-Cloning,Clone a voice in 5 seconds to generate arbitra...,"45,098",Python
6,mastodon / mastodon,"Your self-hosted, globally interconnected micr...","43,926",Ruby
7,AntonioErdeljac / next13-lms-platform,-,115,TypeScript
8,TabbyML / tabby,Self-hosted AI coding assistant,"9,960",TypeScript
9,basecamp / kamal,Deploy web apps anywhere.,"6,761",Ruby
10,godotengine / godot,Godot Engine – Multi-platform 2D and 3D game e...,"73,500",C++
11,vercel / next.js,The React Framework,"111,749",JavaScript
12,ripienaar / free-for-dev,"A list of SaaS, PaaS and IaaS offerings that h...","73,720",HTML
13,aiwaves-cn / agents,An Open-source Framework for Autonomous Langua...,"2,070",Python
14,duckduckgo / tracker-radar,Data set of top third party web domains with r...,"1,182",JavaScript
15,Alamofire / Alamofire,Elegant HTTP Networking in Swift,"39,756",Swift
16,coqui-ai / TTS,🐸💬 - a deep learning toolkit for Text-to-Speec...,"18,409",Python
17,sczhou / ProPainter,[ICCV 2023] ProPainter: Improving Propagation ...,735,Python
18,aras-p / UnityGaussianSplatting,Toy Gaussian Splatting visualization in Unity,521,C#
19,Snailclimb / JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,"137,187",Java
20,WooooDyy / LLM-Agent-Paper-List,"The paper list of the 86-page paper ""The Rise ...","1,099",-
21,MunGell / awesome-for-beginners,A list of awesome beginners-friendly projects.,"56,617",-
22,fmtlib / fmt,A modern formatting library,"17,757",C++
23,meshery / meshery,"Meshery, the cloud native manager","3,246",Go
24,langchain-ai / langchain,⚡ Building applications with LLMs through comp...,"62,583",Python

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:

  A) Song name

  B) Artist name

  C) Last week rank

  D) Peak rank

  E) Weeks on board

  Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [1]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get("https://www.billboard.com/")

In [2]:
#Clicking on the menu
menu=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[1]/div[1]/button')
menu.click()

#Clicking top 100
top = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
top.click()

#Extracting Required Data
data=[i.text.split('\n') for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]')]

driver.close()

#Creating DataFrame:
columns = ['Song name', 'Artist Name', 'Last Weak Rank', 'Peak Rank', 'Weeks on Chart']

Top100 = pd.DataFrame(data, columns=columns)
Top100

,Song name,Artist Name,Last Weak Rank,Peak Rank,Weeks on Chart
0,Vampire,Olivia Rodrigo,9,1,11
1,Paint The Town Red,Doja Cat,1,1,6
2,I Remember Everything,Zach Bryan Featuring Kacey Musgraves,2,1,3
3,Fast Car,Luke Combs,3,2,25
4,Cruel Summer,Taylor Swift,4,3,19
...,...,...,...,...,...
95,Lagunas,Peso Pluma & Jasiel Nunez,-,77,9
96,Sittin' On Top Of The World,Burna Boy,86,80,3
97,Rubicon,Peso Pluma,95,63,11
98,TQM,Fuerza Regida,89,34,17
99,Amargura,Karol G,91,85,5

6. Scrape the details of Highest selling novels.
compare

  A) Book name

  B) Author name

  C) Volumes sold

  D) Publisher

  E) Genre

  url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [4]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [5]:
#Extracting Book Name
book =[i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')]

#Extracting Author Name
author = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')]

#Extracting Volumes sold
vol = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')]

#Extracting Publisher
pub = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')]

#Extracting Genre
gen = [i.text for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')]

driver.close()
print(len(book),len(author),len(vol),len(pub), len(gen))

# Convertingin Dataframe:
Highest_selling_novels=pd.DataFrame({
    "Book Name": book,
    "Author Name":author,
    "Volumes sold":vol,
    "Publisher": pub,
    "Genre" : gen
})

Highest_selling_novels

100 100 100 100 100

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You
have to find the following details:


  A) Name

  B) Year span

  C) Genre

  D) Run time

  E) Ratings

  F) Votes

In [6]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

#opening the website page
driver.get("https://www.imdb.com/list/ls095964455/")

In [7]:
#Extracting Name:
name =[i.text for i in driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')]

# Extracting Year Span
year = [i.text for i in driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')]

#Extracting Genre 
genre = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')]

#Extracting Run time
time = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')]

#Extracting Rating
rating = [i.text for i in driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')]

#Extracting Votes
voting = [i.text for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]')]

driver.close()
print(len(name), len(year), len(genre), len(time), len(rating),len(voting))

#Creating DataFrame
most_watched_tv_series=pd.DataFrame({
    "Name": name,
    "Year span":year,
    "Genre":genre,
    "Run time":time,
    "Ratings":rating,
    "Votes": voting
})
most_watched_tv_series

100 100 100 100 100 100

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,205,249"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,276,583"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,046,328"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"307,522"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"266,599"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,755"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,813"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,126"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,925"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"266,241"

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
    
  A) Dataset name

  B) Data type

  C) Task

  D) Attribute type
 
  E) No of instances

  F) No of attribute G) Year

  Note: - from the home page you have to go to the Show All Dataset page through code.

In [81]:
# Importing Libraries
import pandas as pd
import selenium                                  
from bs4 import BeautifulSoup
from selenium import webdriver                   
from selenium.webdriver.common.by import By      

import warnings                                  
warnings.filterwarnings("ignore")

import time                                      
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

#Importing required exceptions which needs to be handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementClickInterceptedException

# Let's Install automated chrome browser and connect it to web driver
driver = webdriver.Chrome(service=Service())

#maximise the window
driver.maximize_window()

In [82]:
#opening the website page
driver.get("https://archive.ics.uci.edu/")

In [83]:
#clicking all dataset
dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/header/nav/ul/li[1]/a')
dataset.click()

In [84]:
#Clicking collapse
collapse=driver.find_element(By.XPATH,'//label[@class="btn-primary btn-sm btn flex gap-2 rounded-full"]')
collapse.click()

In [85]:
name=[]
datatype=[]
task=[]
instances=[]

while True:
    
    #Extracting Name:
    for i in driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]'):
        name.append(i.text)
    
    #Extracting DataType
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[2]'):
        datatype.append(i.text)
        
    #Extracting task
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[1]'):
        task.append(i.text)
         
    #Extracting instances
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[3]'):
        instances.append(i.text)
  
    #clicking next button
    try:
        nextButton= driver.find_element(By.XPATH,'//button[@class="btn-primary btn-sm btn"][2]')
        nextButton.click()
        time.sleep(3)
    except (NoSuchElementException, ElementClickInterceptedException):
        break

driver.close()
Attributetype=attributetype[:624]
print(len(name),len(datatype),len(task),len(instances),len(no_attribute), len(Attributetype), len(year))

#Creating DataFrame:
data=pd.DataFrame({
    "Dataset Name":name,
    "Data Type":datatype,
    "Task":task,
    "No of Instances":instances})
data

10 10 10 10 10 20 10

,Dataset Name,Data Type,Task,No of Instances
0,Iris,Tabular,Classification,150 Instances
1,Heart Disease,Multivariate,Classification,303 Instances
2,Adult,Multivariate,Classification,48.84K Instances
3,Dry Bean Dataset,Multivariate,Classification,13.61K Instances
4,Diabetes,,,
5,Wine,Tabular,Classification,178 Instances
6,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,569 Instances
7,Car Evaluation,Multivariate,Classification,1.73K Instances
8,Rice (Cammeo and Osmancik),Multivariate,Classification,3.81K Instances
9,Mushroom,Multivariate,Classification,8.12K Instances